-- DROP TABLE  IF EXISTS;
DROP TABLE "PUBLIC"."SHOP_LIST_PRODUCT" IF EXISTS;
DROP TABLE "PUBLIC"."SHOP_LIST" IF EXISTS;
DROP TABLE "PUBLIC"."ORDER_PRODUCT" IF EXISTS;
DROP TABLE "PUBLIC"."ORDERS" IF EXISTS;
DROP TABLE "PUBLIC"."USER" IF EXISTS;
DROP TABLE "PUBLIC"."ORDERS" IF EXISTS;
DROP TABLE "PUBLIC"."USER" IF EXISTS;
DROP TABLE "PUBLIC"."PRODUCT_CATEGORY" IF EXISTS;
DROP TABLE "PUBLIC"."CATEGORY" IF EXISTS;
DROP TABLE "PUBLIC"."PRODUCT" IF EXISTS;
DROP TABLE "PUBLIC"."SPRING_SESSION" IF EXISTS;
DROP TABLE "PUBLIC"."SPRING_SESSION_ATTRIBUTES" IF EXISTS;

CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 4577;

CREATE CACHED TABLE "PUBLIC"."SPRING_SESSION"(
    "PRIMARY_ID" CHAR(36) NOT NULL,
    "SESSION_ID" CHAR(36) NOT NULL,
    "CREATION_TIME" BIGINT NOT NULL,
    "LAST_ACCESS_TIME" BIGINT NOT NULL,
    "MAX_INACTIVE_INTERVAL" INT NOT NULL,
    "EXPIRY_TIME" BIGINT NOT NULL,
    "PRINCIPAL_NAME" VARCHAR(100)
);
ALTER TABLE "PUBLIC"."SPRING_SESSION" ADD CONSTRAINT "PUBLIC"."SPRING_SESSION_PK" PRIMARY KEY("PRIMARY_ID");

CREATE CACHED TABLE "PUBLIC"."SPRING_SESSION_ATTRIBUTES"(
    "SESSION_PRIMARY_ID" CHAR(36) NOT NULL,
    "ATTRIBUTE_NAME" VARCHAR(200) NOT NULL,
    "ATTRIBUTE_BYTES" LONGVARBINARY NOT NULL
);
ALTER TABLE "PUBLIC"."SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "PUBLIC"."SPRING_SESSION_ATTRIBUTES_PK" PRIMARY KEY("SESSION_PRIMARY_ID", "ATTRIBUTE_NAME");

CREATE CACHED TABLE "PUBLIC"."PRODUCT"(
    "PRODUCT_ID" BIGINT NOT NULL SELECTIVITY 100,
    "CREATED_DATE" TIMESTAMP SELECTIVITY 100,
    "MODIFIED_DATE" TIMESTAMP SELECTIVITY 100,
    "DESCRIPTION" VARCHAR(255) SELECTIVITY 97,
    "IMG_URL" VARCHAR(255) SELECTIVITY 100,
    "NAME" VARCHAR(255) SELECTIVITY 100,
    "PRICE" INTEGER NOT NULL SELECTIVITY 33,
    "STOCK_QUANTITY" INTEGER NOT NULL SELECTIVITY 1,
    "CATEGORY_ID" BIGINT SELECTIVITY 1
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("PRODUCT_ID");

CREATE CACHED TABLE "PUBLIC"."CATEGORY"(
    "CATEGORY_ID" BIGINT NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "KURLY_ID" BIGINT,
    "NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("CATEGORY_ID");

CREATE CACHED TABLE "PUBLIC"."PRODUCT_CATEGORY"(
    "PRODUCT_CATEGORY_ID" BIGINT NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "CATEGORY_ID" BIGINT,
    "PRODUCT_ID" BIGINT,
    "ORDER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_39" PRIMARY KEY("PRODUCT_CATEGORY_ID");

CREATE CACHED TABLE "PUBLIC"."USER"(
    "USER_ID" BIGINT NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "EMAIL" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PICTURE" VARCHAR(255),
    "ROLE" INTEGER
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("USER_ID");

CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ORDER_ID" BIGINT NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "STATUS" VARCHAR(255),
    "USER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ORDER_ID");

CREATE CACHED TABLE "PUBLIC"."USER"(
    "USER_ID" BIGINT NOT NULL AUTO_INCREMENT,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "EMAIL" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PICTURE" VARCHAR(255),
    "ROLE" INTEGER
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("USER_ID");

CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ORDER_ID" BIGINT NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "STATUS" VARCHAR(255),
    "USER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ORDER_ID");
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FKEL9KYL84EGO2OTJ2ACCFD8MR7" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("USER_ID") NOCHECK;

CREATE CACHED TABLE "PUBLIC"."ORDER_PRODUCT"(
    "ORDER_PRODUCT_ID" BIGINT NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "COUNT" INTEGER NOT NULL,
    "ORDER_PRICE" INTEGER NOT NULL,
    "ORDER_ID" BIGINT,
    "PRODUCT_ID" BIGINT
);
ALTER TABLE "PUBLIC"."ORDER_PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ORDER_PRODUCT_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_PRODUCT;
ALTER TABLE "PUBLIC"."ORDER_PRODUCT" ADD CONSTRAINT "PUBLIC"."FKL5MNJ9N0DI7K1V90YXNTHKC73" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."ORDERS"("ORDER_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ORDER_PRODUCT" ADD CONSTRAINT "PUBLIC"."FKHNFGQYJX3I80QOYMRSSLS3KNO" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("PRODUCT_ID") NOCHECK;

CREATE CACHED TABLE "PUBLIC"."SHOP_LIST"(
    "SHOP_LIST_ID" BIGINT NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "USER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."SHOP_LIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("SHOP_LIST_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SHOP_LIST;
ALTER TABLE "PUBLIC"."SHOP_LIST" ADD CONSTRAINT "PUBLIC"."FKHG031RCHUAW8J2ID6U8U17AD1" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("USER_ID") NOCHECK;

CREATE CACHED TABLE "PUBLIC"."SHOP_LIST_PRODUCT"(
    "SHOP_LIST_PRODUCT_ID" BIGINT NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "MODIFIED_DATE" TIMESTAMP,
    "COUNT" INTEGER NOT NULL,
    "SHOP_LIST_PRICE" INTEGER NOT NULL,
    "PRODUCT_ID" BIGINT,
    "SHOP_LIST_ID" BIGINT
);
ALTER TABLE "PUBLIC"."SHOP_LIST_PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("SHOP_LIST_PRODUCT_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SHOP_LIST_PRODUCT;
ALTER TABLE "PUBLIC"."SHOP_LIST_PRODUCT" ADD CONSTRAINT "PUBLIC"."FKQK3AN0THITUTN4MDNSJPSS7QU" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("PRODUCT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."SHOP_LIST_PRODUCT" ADD CONSTRAINT "PUBLIC"."FKN5OP7HA81L750R6YKNG1JBVP2" FOREIGN KEY("SHOP_LIST_ID") REFERENCES "PUBLIC"."SHOP_LIST"("SHOP_LIST_ID") NOCHECK;

