database: hsqldb
spring:
  profiles.active: local
  profiles.include: oauth,kafka,db
  session.store-type: jdbc

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/sisishop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#    data: classpath*:db/${database}/data.sql # db data 초기화하고 싶을 때 이용

#  jpa:
#    hibernate:
#      ddl-auto: update #create # , create-drop
#    properties:
#      hibernate:
#  #     show_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

ubic:
  orders:
    productListPageSize: 28
    productDetailPageSize: 8
    djangoServerUrl: http://ubic-env-08221710.ap-northeast-2.elasticbeanstalk.com

# spring.profiles.include=oauth
#spring.session.store-type: jdbc
#server:
#  servlet:
#    session:
#      timeout: 5s #30m # 디폴트값 30분
---
spring:
  profiles: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/sisishop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create # , create-drop update #
    properties:
      hibernate:
        #     show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

