database: hsqldb
spring:
  profiles.active: local
  profiles.include: oauth,kafka,db
  session.store-type: jdbc


#logging.level:
#  org.hibernate.SQL: debug # [로그 주석]
# org.hibernate.type: trace

ubic:
  orders:
    productListPageSize: 28
    productDetailPageSize: 4
    djangoServerUrl: http://ubic-env-08221710.ap-northeast-2.elasticbeanstalk.com
    localDjangoServerUrl: http://127.0.0.1:8000
    dashBoardProductListPageSize: 4

# spring.profiles.include=oauth
#spring.session.store-type: jdbc
#server:
#  servlet:
#    session:
#      timeout: 5s #30m # 디폴트값 30분
---
spring:
  profiles: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/sisishop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # create # , create-drop update
    properties:
      hibernate:
        #     show_sql: true

        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

        format_sql: true

